### ISSUE TITLE
Some propositions

### ISSUE THREAD

**Issue by huumanoid** [xSlOom/XatAPI#1]
Hello @xSlOom I've just checked out your library and it's awesome!

There are some improvements which I want to propose:

### Make your API output more structured
I mean, API is intended to be used by programs, but your library is still for humans.

What if my program wants to fetch user's ID by regname? It seems that I have to write the following code:
```js
const api = require('xatapi')

let id = null

api.getID('xSloom', (res) => id = /: (\d+)/.exec(res))
```

But it's preferable to do something like this:
```js
const api = require('xatapi')

let id = null

api.getID('xSloom', (err, res) => {
  if (err != null) {
    throw err; // oh no! Not found/ID must be numeric etc..
  }
  id = res // yes, that's it!
  console.log(id) // 10000070
})
```
That's how we do it in nodejs. This is nodejs-styled callbacks. First argument is always an error. If `err` is `null`, then everything is OK. Otherwise, `err` probably should be an instance of `Error` class.

### Add search
Yeah, I think that awesome stuff should be placed there

### Xat API documentation
This proposition is not an important thing, but it would be awesome if we have a detailed Xat Web API documentation there, like the one for xat chat protocol in [xat-client repository](https://github.com/huumanoid/xat-client).

Once again, thank you for your awesome stuff!
Feel free to ask, I would be happy to answer.

**Comment by xSlOom** [comment]
Hey @huumanoid, thanks again for your feedback.

You may have to edit the xat.js (do a pull request) with the improvements (if you want) and see if I can add it on the next update. 

This library was made faster as possible since I had already something working. And the library is "xatlib" and not "xatapi" as you mentioned on your example. 😄 

I have a question about the callback, how it would look on the function?

About "Add search", do you mean the thing I made days ago with xat.com/web_gear/chat/search.php ? If yes, why not, it can be a thing on my todolist.

And yeah, the documentation isn't complete at all, but if you have any ideas of what I can add, I'll take it.

Thanks again. :) 

EDIT:

I did an update on the current file xat.js if you want to take a look and see if it's good so i can update the library after.

**Comment by huumanoid** [comment]
I'm going to add some tests to project, it's good when API is covered with tests.

Yes you are right about callbacks. Actually, you don't need to pass `null` as second argument.
Probably it's a good idea to pass an instance of `Error` class to callback.
```js
return callback(new Error("You must specify and ID blah blah"))
```
There are several advantages of this approach:
1) When `Error` instance created, it's automatically filled with stack trace.
2) You may specify additional fields of `Error` object. Right now your library throws two general types of error:
    * invalid argument passed to function (incorrect usage)
    * id/regname/etc doesn't exists

It's very handy to distinguish this types of errors in application itself.
In the first case, probably it's a programmer's error, so exception should be thrown (application is in illegal state).
In the second case we should just inform user that id doesn't exists.

**Note: you don't have to design good error system right now**
But this may be suitable in future. If you then change type of `err` from `String` to `Error`, you will break backward compatibility, this is not the case for the library.

Ok I'm going to write a part of web api documentation and let you review it.

**Comment by xSlOom** [comment]
I see. 

I feel like a noob on doing that things and not knowing how to handle errors correctly.. I'll wait for your tests to see more about and do some tests on my side.
